# Generated by Django 6.0.1 on 2026-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
