# Generated by Django 6.0.1 on 2026-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
