# Generated by Django 6.0.1 on 2026-02-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('done', 'Done'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='games',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
